import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "./_providers/ReactQueryProvider";
import { fetchPopularSubreddits } from "@/lib/reddit";
import Link from "next/link";
import { Inter } from "next/font/google";
import { SubredditInfo } from "@/types/reddit";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const subreddits = await fetchPopularSubreddits();
  return (
    <ReactQueryProvider>
      <html lang="en" className={inter.className}>
        <body
          className={`grid grid-cols-1 md:grid-cols-[250px_1fr] min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Sidebar */}
          <Sidebar subreddits={subreddits} />
          {/* Main Content */}
          <main className="p-4">{children}</main>
        </body>
      </html>
    </ReactQueryProvider>
  );
}

async function Sidebar({ subreddits }: { subreddits: SubredditInfo[] }) {
  return (
    <aside className="bg-zinc-100 dark:bg-zinc-900 p-4 border-r border-zinc-200 dark:border-zinc-700 sticky top-0 h-screen overflow-y-auto">
      <h2 className="text-xl font-extrabold mb-4 tracking-wide">reddit<span className="text-gray-400 font-semibold">Lite</span></h2>
      <ul className="space-y-2 text-sm">
        {!subreddits.length ? <SubredditSkeleton /> :
          subreddits.map((sr: SubredditInfo) => (
            <li key={sr.name}>
              <Link prefetch={true} href={sr.url} className="hover:underline text-blue-600">
                {sr.name}
              </Link>
            </li>
          ))}
      </ul>
    </aside>
  )
}

function SubredditSkeleton() {
  return (
    <div className="animate-pulse p-4 border rounded-lg space-y-2">
      <div className="h-4 bg-zinc-300 dark:bg-zinc-700 w-3/4 rounded" />
    </div>
  );
}